### ISSUE TITLE
Launch countdown's timezone selector finicky at low window widths/heights

### ISSUE THREAD

**Issue by RoryStolzenberg** [LukeNZ/spacexstats#39]
At window widths below ~1400px and heights below ~900px, the timezone dropdown for the NextLaunch card overlaps with the countdown, preventing the user from making a selection. When a user mouses over a choice in the dropdown, a text selection cursor is displayed and the dropdown collapses.

Screenshot: ![finicky dropdown](http://i.imgur.com/VSgkw63.png)

(another h/t to NoidedN8)

**Comment by LukeNZ** [comment]
Fixed via commit 0fae00f. Thanks Rory.
